### ISSUE TITLE
Hafs vs Hafs smart

### ISSUE THREAD

**Issue by ghost** [thetruetruth/quran-data-kfgqpc#1]
asalamu alaykum

I am looking to make an app for all rewayas of the quran inshallah, as i have found, as someone who reads with qaloon, that there are not many good resources for other rewayas beyond hafs an asim of the same quality of quran.com. This will mean I will have to include the rewayah of hafs an asim; which of hafs and hafs smart would you reccomend for a website and which would you reccomend for an app? 

jazak allah khaira

**Comment by thetruetruth** [comment]
Waalaikumsalam,

Masha Allah, good for you. I try to answer in my best knowledge.
You want to make an app, i think its best to have one default hafs and let
user choose which one they would prefer. Same goes to the rewayas. This
might be good description for your app where it shine than others.

**Comment by ghost** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
